### ISSUE TITLE
Why iyts not working??

### ISSUE THREAD

**Issue by Tafsir-Bhuiyan** [Virus18sp/qb-Medsystem#2]
Brother Its not working ;(

**Comment by Virus18sp** [comment]
This is old friend this was made for the very early qbcore version, just update it.

**Comment by Tafsir-Bhuiyan** [comment]
Can u plz update this 😁😁

**Comment by Virus18sp** [comment]
> Can u plz update this 😁😁

Can you send me screenshot about what is the problem you get? If you see and error on console or F8?

**Comment by Virus18sp** [comment]
Pushed an update, try it.
